fix(action): wip test some stuffs

diff --git a/.github/actions/autodevops-create-db/scripts/copy-secret b/.github/actions/autodevops-create-db/scripts/copy-secret
--- a/.github/actions/autodevops-create-db/scripts/copy-secret
+++ b/.github/actions/autodevops-create-db/scripts/copy-secret
@@ -1,12 +1,18 @@
 #!/usr/bin/env bash
 
-if [ "$SOCIALGOUV_PRODUCTION" ]; then
-  DB_SECRET_NAME=pg-user
-elif [ "$SOCIALGOUV_PREPRODUCTION" ]; then
-  DB_SECRET_NAME=pg-user-preprod
-else
-  DB_SECRET_NAME="pg-user-${BRANCH_SLUG}"
+if [ -z "$1" ]; then
+  echo "Missing required argument 1 secret name"
+  exit 1
 fi
-kubectl get secret $DB_SECRET_NAME --namespace=$NAMESPACE -o yaml \
+if [ -z "$2" ]; then
+  echo "Missing required argument 2 source namespace"
+  exit 1
+fi
+if [ -z "$3" ]; then
+  echo "Missing required argument 3 target namespace"
+  exit 1
+fi
+
+kubectl get secret "$1" --namespace="$2" -o yaml \
   | sed 's/namespace: .*//' \
-  | kubectl -n $JOB_NAMESPACE apply -f -
+  | kubectl -n "$3" apply -f -
